timekeeper/auths/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import PasswordsChangeView, PasswordsResetView

app_name = "auths"

urlpatterns = [
    path("", views.login_user, name="login"),
    path("logout", views.logout_user, name="logout"),
    path("register", views.register_user, name="register"),
    path("delete_user/<int:user_id>", views.delete_user, name="delete_user"),
    path('change-password/', PasswordsChangeView.as_view(
        template_name='auths/change-password.html'), name="change_password"),
    path('reset-password/', PasswordsResetView.as_view(
        template_name='auths/change-password.html'), name="password_reset"),
    path('reset-password-success/', views.reset_password_success,
         name="password_reset_success"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='auths/change-password-form.html'), name="password_reset_confirm"),
    path('reset/done/', views.reset_password_complete,
         name="password_reset_complete"),
]

timekeeper/backend/urls.py
from django.urls import path
from . import views

app_name = "backend"

urlpatterns = [
    path("", views.index, name="index"),
    path("history", views.history, name="history"),
    path("include", views.include, name="include"),
    path("offday", views.off_day, name="off_day"),
    path("users", views.user_list, name="userList"),
    path("users/<int:user_id>", views.user, name="user"),
    path("delete_record/<int:record_id>",
         views.delete_record, name="delete_record"),
    path("export", views.export_records, name="export_records")
]

timekeeper/timekeeper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend.urls')),
    path('auths/', include('auths.urls')),
    path('auths/', include('django.contrib.auth.urls')),
]

handler404 = 'backend.views.handler404'
handler403 = 'backend.views.handler403'
handler500 = 'backend.views.handler500'

timekeeper/backend/models.py
import calendar
from datetime import datetime, timedelta
from django.db import models
from django.db.models import Q
from django.utils.timezone import now


from auths.models import CustomUser


class Record(models.Model):

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date = models.DateTimeField(default=now)
    action = models.CharField(max_length=20, default='')
    status = models.CharField(max_length=20, default='Wating Approval')
    break_duration = models.IntegerField(default=0)
    remarks = models.CharField(max_length=255, default='')
    off_day = models.BooleanField(default=False)

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.sixty_seconds = 60
        self.zero_hour = 0
        self.twelve_hours = 12
        self.twenty_four_hours = 24

    def get_records(self, user, year=datetime.now().year, week=int(datetime.now().strftime("%V")), month=None):
        query = Q(user=user, date__year=year)

        if month:
            query.add(Q(date__month=month), "AND")
        else:
            query.add(Q(date__week=week), "AND")

        return Record.objects.filter(query).order_by("date__day", "date__hour")

    def create_record(self, user, status, action, date=None, time=None, break_duration=0, remarks=None):
        record = Record()
        record.user = user
        record.status = status
        record.action = action
        if action == "Clock-out":
            record.break_duration = break_duration

        if date:
            record.date = self.get_date(date, time)

        if remarks:
            record.remarks = remarks

        record.save()

    def create_off_day(self, username, date):
        user = CustomUser.objects.filter(username=username)[0]
        
        off_day = Record()
        off_day.user = user
        off_day.date = self.get_date(date, "00:00")
        off_day.off_day = True
        off_day.status = 'Approved'
        off_day.save()

    def get_date(self, date, time):
        datetime_str = f'{date} {time}'
        return datetime.strptime(datetime_str, "%Y-%m-%d %H:%M")

    def calculate_worked_hours(self, records):
        worked_hours = timedelta(0)
        break_duration_sum = 0
        check_in_records = list(
            filter(
                lambda record: record.action == "Clock-in" and record.status == "Approved",
                records,
            )
        )

        for record in check_in_records:
            record_index = next(i for i, x in enumerate(
                list(records)) if x.id == record.id)

            if record_index + 1 < len(records) and (
                    records[record_index].date.day == records[record_index + 1].date.day
                    and records[record_index + 1].action == "Clock-out"
                    and records[record_index + 1].status == "Approved"
            ):
                worked_hours += records[record_index +
                                        1].date - records[record_index].date
                break_duration_sum += records[record_index + 1].break_duration

        worked_seconds = worked_hours.seconds - \
            (break_duration_sum * self.sixty_seconds)

        return "{:02}h{:02}".format(worked_seconds // 3600, worked_seconds % 3600 // 60)

    def get_weeks_in_month(self, year, month):
        first_week = int(datetime(year, month, 1).strftime('%V'))
        last_day_of_month = calendar.monthrange(year, month)[1]
        last_week = int(datetime(year, month, last_day_of_month).strftime('%V')) + 1

        return [*range(first_week, last_week)]

    def get_week_days(self, year, week_number):
        date = f'{year}-W{week_number}'
        reference_day = datetime.strptime(date + '-1', "%Y-W%W-%w")
        fist_day = self.ordinal_number(reference_day.day)

        reference_day = reference_day + timedelta(days=6)
        last_day = self.ordinal_number(reference_day.day)

        return f'{fist_day} - {last_day}'

    def ordinal_number(self, number):
        suffix = None
        match number:
            case 1 | 21 | 31:
                suffix = 'st'
            case 2 | 22:
                suffix = 'nd'
            case 3 | 23:
                suffix = 'rd'
            case _:
                suffix = 'th'
        return f'{number}{suffix}'

    def get_filter_options(self, year, month):
        options = {}
        weeks = self.get_weeks_in_month(year, month)
        for week in weeks:
            week_days = self.get_week_days(year, week)
            options[week] = week_days
        return options
    

timekeeper/backend/views.py
from datetime import datetime

from auths.models import CustomUser
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect, render
import json

from .utils.workbook import create_file
from .models import Record

CURRENT_WEEK = f"year={datetime.now().year}&month={datetime.now().month}&week={datetime.now().strftime('%V')}"

MONTHS = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December',
}



def index(request):
    return redirect("/auths")


def history(request):
    if not request.user.is_authenticated:
        messages.success(request, "You must login to access this page")
        return redirect("/auths")
    elif not request.user.is_password_reset:
        messages.success(
            request, "You must reset your password before accessing the application")
        return redirect("/auths/change-password")

    if request.method == "POST":
        save_record(request)

        return redirect(f"/history?{CURRENT_WEEK}")
    else:
        user = request.user
        context = query_records(request, user)

        context = {
            **context,
            "isHistory": True,
        }
        return render(request, "backend/history.html", context)


def query_records(request, user):
    year = int(request.GET.get('year'))
    week = int(request.GET.get('week'))
    month = int(request.GET.get('month'))

    try:
        record = Record()
        passed_month = month if week == -1 else None
        records = record.get_records(user, year, week, passed_month)
        earliest_record = (
            Record.objects.filter(user=user).earliest(
                "date__year").date.year
        )
        options = record.get_filter_options(year, month)

        context = {
            "records": records,
            "workedHours": record.calculate_worked_hours(records),
            "years": range(earliest_record, datetime.now().year + 1),
            "selectedYear": year,
            "months": MONTHS,
            "selectedMonth": month,
            "selectedWeek": week,
            "options": options
        }
    except:
        context = {
            "records": [],
            "years": range(datetime.now().year, datetime.now().year + 1),
            "selectedYear": year,
            "months": MONTHS,
            "selectedMonth": month,
            "selectedWeek": week,
            "options": {}
        }

    return context


def save_record(request):
    user = request.user
    action = request.POST.get("action")
    break_duration = request.POST.get("breakDuration")

    record = Record()
    record.create_record(user, "Approved", action,
                         break_duration=break_duration)


def include(request):
    if not request.user.is_authenticated:
        messages.success(request, "You must login to access this page")
        return redirect("/auths")
    elif not request.user.is_password_reset:
        messages.success(
            request, "You must reset your password before accessing the application")
        return redirect("/auths/change-password")

    if request.method == "POST":
        user = request.user
        date = request.POST.get("date")
        clockin_time = request.POST.get("clockInTime")
        clockout_time = request.POST.get("clockOutTime")
        break_duration = request.POST.get("breakDuration") or 0
        remarks = request.POST.get("remarks")

        record = Record()

        if clockin_time:
            record.create_record(
                user, "Wating Approval", 'Clock-in', date, clockin_time, break_duration, remarks)

        if clockout_time:
            record.create_record(
                user, "Wating Approval", 'Clock-out', date, clockout_time, break_duration, remarks)

        return redirect(f"/history?{CURRENT_WEEK}")
    else:
        return render(request, "backend/include.html")

def off_day(request):
    if not request.user.is_authenticated:
        messages.success(request, "You must login to access this page")
        return redirect("/auths")
    elif not request.user.is_password_reset:
        messages.success(
            request, "You must reset your password before accessing the application")
        return redirect("/auths/change-password")

    if not request.user.is_staff:
        messages.success(request, "You can't access this page")
        return redirect(f"/history?{CURRENT_WEEK}")
    
    if request.method == "POST":
        user = request.POST.get("user")
        date = request.POST.get("date")

        off_day = Record()
        off_day.create_off_day(user, date)

        return redirect(f"/history?{CURRENT_WEEK}")
    else:
        users = CustomUser.objects.all()
        user_names = {}
        for user in users.iterator():
            user_names[user.username] = f'{user.first_name} {user.last_name}'

        context = {"users": user_names}
        return render(request, "backend/offDay.html", context)


def user_list(request):
    if not request.user.is_authenticated:
        messages.success(request, "You must login to access this page")
        return redirect("/auths")
    elif not request.user.is_password_reset:
        messages.success(
            request, "You must reset your password before accessing the application")
        return redirect("/auths/change-password")

    if not request.user.is_staff:
        messages.success(request, "You can't access this page")
        return redirect(f"/history?{CURRENT_WEEK}")


    users = CustomUser.objects.all().exclude(username='admin')
    earliest_record = (
        Record.objects.earliest(
            "date__year").date.year
    )
    
    context = {
        "users": users,
        "years": range(earliest_record, datetime.now().year + 1),
        "months": MONTHS,
        "selectedYear": datetime.now().year,
        "selectedMonth": datetime.now().month
    }
    return render(request, "backend/userList.html", context)


def user(request, user_id):
    if not request.user.is_authenticated:
        messages.success(request, "You must login to access this page")
        return redirect("/auths")
    elif not request.user.is_password_reset:
        messages.success(
            request, "You must reset your password before accessing the application")
        return redirect("/auths/change-password")

    if not request.user.is_staff:
        messages.success(request, "You can't access this page")
        return redirect(f"/history?{CURRENT_WEEK}")

    listed_user = CustomUser.objects.get(id=user_id)
    record = Record()

    if request.method == "POST":
        if request.POST.get("username"):
            listed_user.username = request.POST.get("username")
            listed_user.first_name = request.POST.get("firstName")
            listed_user.last_name = request.POST.get("lastName")
            listed_user.email = request.POST.get("email")
            if request.POST.get("role"):
                listed_user.is_staff = True
            else:
                listed_user.is_staff = False
            listed_user.save()
        else:
            edited_record = Record.objects.get(id=request.POST.get("id"))
            date = request.POST.get("date")
            time = request.POST.get("time")
            
            edited_record.date = record.get_date(date, time)
            edited_record.action = request.POST.get("action")
            edited_record.status = request.POST.get("status")
            edited_record.save()

    context = query_records(request, listed_user)

    context = {
        **context,
        "listed_user": listed_user,
        "isHistory": False,
    }

    return render(request, "backend/user.html", context)


def delete_record(request, record_id):
    if not request.user.is_authenticated or not request.user.is_staff:
        messages.success(request, "You must login to access this page")
        return redirect("/auths")
    
    if request.method == "DELETE":
        print("Record: ", record_id)
        record = Record.objects.get(pk=record_id)
        record.delete()
        return HttpResponseRedirect("/history")
    
    
def export_records(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        messages.success(request, "You must login to access this page")
        return redirect("/auths")
    elif not request.user.is_password_reset:
            messages.success(
                request, "You must reset your password before accessing the application")
            return redirect("/auths/change-password")

    data = json.loads(request.body.decode('utf-8'))
    year =  data.get('year')
    weeks = data.get('weeks')
    # weeks = [number]
    stream = create_file(year, weeks)

    response = HttpResponse(content=stream, content_type="application/vnd.ms-excel")
    return response


def handler404(request, exception):
    context = {"error_code": 404}
    return render(request, "backend/error.html", context)


def handler403(request, exception):
    context = {"error_code": 403}
    return render(request, "backend/error.html", context)


def handler500(request, exception=''):
    context = {"error_code": 500}
    return render(request, "backend/error.html", context)

timekeeper/backend/templates/backend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="{% static 'images/favico.ico' %}"
      type="image/x-icon"
    />

    <!-- CSS only -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link
      href="{% static 'css/bootstrap-icons-1.10.3/bootstrap-icons.css' %}"
      rel="stylesheet"
    />

    <!-- JS only-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>TimeKeeper</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" 
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
          style="line-height: 0; padding: 0; border: none;">
          <span class="navbar-toggler-icon"></span>
        </button>

        <a
          class="navbar-brand"
          href="{% url 'backend:history' %}?year={% now 'Y' %}&month={% now 'm' %}&week={% now 'W' %}"
          style="
            font-family: Georgia;
            font-size: min(6vw, 1.5rem);
            letter-spacing: 0;
            font-style: italic;
            margin: 0;
          "
        >
          <img
            src="{% static 'images/logo_512x512.png' %}"
            style="width: 25%; max-width: 48px; margin-right: min(20%, .5em)"
            alt="Christian Endeavour Holiday Centres"
            id="logo"
          />
          TimeKeeper</a
        >

        <div class="float-end logout-mobile">
          <a class="nav-link" href="{% url 'auths:logout' %}">
            <i class="bi bi-box-arrow-right mx-2" style="font-size:24px"></i>
          </a>
        </div>

        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarNav" style="margin-left: 1em">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a
                class="nav-link {% if 'history' in request.path %}active{% endif %}"
                aria-current="page"
                href="{% url 'backend:history' %}?year={% now 'Y' %}&month={% now 'm' %}&week={% now 'W' %}"
                >History</a
              >
            </li>
            <li class="nav-item">
              {% if user.is_staff %}
              <div class="dropdown">
                <button 
                  class="nav-link dropdown-toggle {% if 'include' in request.path or 'offday' in request.path %}active{% endif %}" 
                  type="button" 
                  id="dropdownMenuButton" 
                  data-toggle="dropdown" 
                  aria-haspopup="true" 
                  aria-expanded="false">
                  Include
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a
                    class="dropdown-item"
                    href="{% url 'backend:include' %}"
                    >Record</a
                  >
                  <a
                    class="dropdown-item"
                    href="{% url 'backend:off_day' %}"
                    >Day Off</a
                  >
                </div>
              </div>
              {% else %}
              <a
                class="nav-link {% if 'include' in request.path %}active{% endif %}"
                href="{% url 'backend:include' %}"
                >Include</a
              >
              {% endif %}
            </li>
            {% if user.is_staff %}
            <li class="nav-item">
              <a
                class="nav-link {% if 'users' in request.path %}active{% endif %}"
                href="{% url 'backend:userList' %}"
                >User List</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if 'register' in request.path %}active{% endif %}"
                href="{% url 'auths:register' %}"
                >Register</a
              >
            </li>
            {% endif %}
            <li class="nav-item">
              <a
                class="nav-link {% if 'password' in request.path %}active{% endif %}"
                href="{% url 'auths:change_password' %}"
                >Change Password</a
              >
            </li>
            <li class="nav-item">
              <button
                type="button"
                class="exportButton nav-link"
                data-bs-toggle="modal"
                data-bs-target="#exportModal"
                data-toggle="modal"
                data-target="#exportModal"
              >
                Export Records
                <i class="bi bi-file-earmark-arrow-up"></i>
              </button>
            </li>
          </ul>
        </div>
        
        <div class="float-end logout-desktop">
          <a class="nav-link" href="{% url 'auths:logout' %}">
            <i class="bi bi-box-arrow-right mx-2" style="font-size:24px"></i>
          </a>
        </div>
        {% endif %}
      </div>
    </nav>

    <div class="container mx-auto mt-3" style="max-width: 1200px; width: 90%">
      {% if messages %} {% for message in messages %}

      <div
        class="alert alert-warning alert-dismissible fade show my-2"
        role="alert"
      >
        {{ message }}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>

      {% endfor %} {% endif %} {% block content %} {% endblock %}
    </div>

    {% include './modalConfirm.html' %}
    
  </body>
</html>

timekeeper/backend/templates/backend/error.html
{% extends 'backend/base.html' %} {% block content%}
<div>
  {% if error_code == 404 %}
  <h2>Sorry, this page does not exist</h2>
  {% elif error_code == 403 %}
  <h2>You are not authorized to access this page</h2>
  {% else %}
  <h2>There was an error</h2>
  {% endif %}
</div>
{% endblock %}

timekeeper/backend/templates/backend/history.html
{% extends 'backend/base.html' %} {% load static %} {% block content %}
<div class="clockContainer w-100 mb-3 text-center">
  <h2 class="clock fs-1" id="clock">00:00:00</h2>
  <form action="" method="post">
    {% csrf_token %}

    <div class="input-group flex-nowrap my-2 justify-content-center">
      <div class="input-group-text">
        <input type="submit" name="action" value="Clock-in" class="btn" />
      </div>
      <div class="input-group-text">
        <input
          type="button"
          name="action"
          value="Clock-out"
          class="btn"
          data-bs-toggle="modal"
          data-bs-target="#confirmModal"
          data-toggle="modal"
          data-target="#confirmModal"
          onclick="showRegisterConfirmModal('register')"
        />
      </div>
    </div>
  </form>
</div>

{% include './historyTable.html' %}

<script src="{% static 'js/history.js' %}"></script>
{% endblock content %}

timekeeper/backend/templates/backend/include.html
{% extends 'backend/base.html' %} {% load static %} {% block content%}
<div class="my-2 text-center">
  <h2 class="mb-3 fs-1">Include record</h2>
  <form action="" method="post">
    {% csrf_token %}
    <div class="input-group flex-nowrap my-2">
      <label class="input-group-text" for="date">Date</label>
      <input type="date" class="form-control" name="date" />
    </div>
    
    <div class="input-group flex-nowrap my-2">
      <input type="time" class="form-control" name="clockInTime" />
      <label class="input-group-text" for="clockInTime">Clock-in Time*</label>
    </div>

    <div class="input-group flex-nowrap my-2">
      <label class="input-group-text" for="clockOutTime">Clock-out Time*</label>
      <input type="time" class="form-control" name="clockOutTime" />
    </div>

    <div id="breakDuration" class="input-group flex-nowrap my-2">
      <input type="number" min="0" class="form-control" name="breakDuration" />
      <label class="input-group-text">Break (in minutes)**</label>
    </div>

    <div id="remark" class="input-group flex-nowrap my-2">
      <textarea class="form-control" name="remarks"></textarea>
      <label class="input-group-text">Remarks</label>
    </div>

    <p>
      *It is not necessary to fill both times, just the ones you did not register
      <br>
      **Break time will only be registered when clock-out time is filled
    </p>

    <input
      type="submit"
      class="btn btn-primary"
      value="Include Record"
      required
    />
  </form>
</div>
<script src="{% static 'js/include.js' %}"></script>
{% endblock %}

timekeeper/backend/templates/backend/modalConfirm.html
{% load static %}

<div
  class="modal fade"
  id="confirmModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="confirmModal"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmModalTitle"></h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          data-bs-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div id="delete-modal-content" hidden>
          <div id="modal-content">
            <p>
              Are you sure you want to delete the
              <span id="deletedDataType"></span>
              :
            </p>
            <p class="text-center"><strong id="deletedDataTitle"></strong></p>
          </div>

          <div class="modal-buttons" style="float: right">
            <button
              type="button"
              class="btn btn-danger"
              onclick="handleDelete()"
            >
              Delete
            </button>
            <button
              type="button"
              class="btn btn-secondary"
              data-dismiss="modal"
              data-bs-dismiss="modal"
            >
              Close
            </button>
          </div>
        </div>

        <div id="register-modal-content" hidden>
          <div id="modal-content">
            <div
              class="input-group mb-3"
              style="max-width: 15em; margin: 0 auto"
            >
              <span class="input-group-text">Break (in minutes)</span>
              <input
                type="number"
                id="breakDuration"
                min="0"
                class="form-control"
                value="0"
              />
            </div>
          </div>

          <div class="modal-buttons" style="float: right">
            <button
              type="button"
              class="btn btn-primary"
              onclick="handleRegister()"
            >
              Register
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/modalConfirm.js' %}"></script>

timekeeper/backend/templates/backend/user.html
{% extends 'backend/base.html' %} {% block content%} {% load static %}

<div>
  {% include 'auths/volunteerForm.html' %} {% include './historyTable.html' %}
</div>

<script src="{% static 'js/user.js' %}"></script>
{% endblock %}

timekeeper/backend/templates/backend/userList.html
{% extends 'backend/base.html' %} {% block content%} {% load static %}

<div class="my-2 text-center">
  {% csrf_token %}
  <h2 class="mb-3 fs-1">Volunteers</h2>

  <div
    class="modal fade"
    id="exportModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="exportModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      {% csrf_token %}
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exportModalLabel">Export Records</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <nav aria-label="Week/Month navigation" class="border rounded mb-4" style="width: fit-content; margin: 0 auto">
            <div class="topSection border-bottom">
              <select class="yearExport border-0 py-1" onchange="updateCheckboxes()" style="width: 100%; text-align: center">
                {% for year in years %}
                <option value="{{year}}" label='{{year}}' 
                  {% if year == selectedYear|add:0 %} selected {% endif %}
                >
                {% endfor %}
              </select>
              <hr style="margin: 0">
              
              <select class="monthExport border-0 py-1" onchange="updateCheckboxes()" style="width: 100%; text-align: center">
                {% for key, value in months.items %}
                <option value="{{key}}" label="{{value}}"  
                  {% if key == selectedMonth|add:0 %} selected {% endif %}
                ></option>
                {% endfor %}
              </select>
            </div>
          </nav>

          <div class="checkboxes"></div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" onclick="downloadFile()">Export Records</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>
        </div>
      </div>
    </div>
  </div>

  <table class="table table-striped">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th></th>
    </tr>

    {% for user in users %}
    <tr>
      <td>{{ user.id }}</td>
      <td>{{ user.first_name }} {{ user.last_name }}</td>
      <td>
        <a
          class="editIcon btn btn-primary"
          href="{% url 'backend:user' user.id %}?year={% now 'Y' %}&month={% now 'm' %}&week={% now 'W' %}"
        >
          <i class="bi bi-pen"></i>
        </a>

        <button
          type="button"
          class="btn btn-danger"
          data-bs-toggle="modal"
          data-bs-target="#confirmModal"
          data-toggle="modal"
          data-target="#confirmModal"
          onclick="showDeleteConfirmModal('user', '{{ user.first_name }} {{ user.last_name }}', {{ user.id }})"
        >
          <i class="bi bi-trash"></i>
        </button>
      </td>
    </tr>
    {% endfor %}
  </table>
</div>

<script src="{% static 'js/userList.js' %}"></script>

{% endblock %}